version: "3.3"
services:
  rabbitmq:
    container_name: "discord_bot-rabbitmq"
    image: rabbitmq:3.8.5-alpine
    restart: always
  celery:
    container_name: "discord_bot-celery"
    build: .
    restart: always
    depends_on:
      - rabbitmq
    working_dir: "/app"
    command: python -O cli.py start-celery-worker
  bot:
    container_name: "discord_bot-bot"
    restart: always
    build: .
    depends_on:
      - rabbitmq
      - celery
    working_dir: "/app"
    command: python -O cli.py start-server
